/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { PatientService } from "../patient.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { PatientCreateInput } from "./PatientCreateInput";
import { Patient } from "./Patient";
import { PatientFindManyArgs } from "./PatientFindManyArgs";
import { PatientWhereUniqueInput } from "./PatientWhereUniqueInput";
import { PatientUpdateInput } from "./PatientUpdateInput";
import { DoctorProgressNoteFindManyArgs } from "../../doctorProgressNote/base/DoctorProgressNoteFindManyArgs";
import { DoctorProgressNote } from "../../doctorProgressNote/base/DoctorProgressNote";
import { DoctorProgressNoteWhereUniqueInput } from "../../doctorProgressNote/base/DoctorProgressNoteWhereUniqueInput";
import { NurseMedicationChartFindManyArgs } from "../../nurseMedicationChart/base/NurseMedicationChartFindManyArgs";
import { NurseMedicationChart } from "../../nurseMedicationChart/base/NurseMedicationChart";
import { NurseMedicationChartWhereUniqueInput } from "../../nurseMedicationChart/base/NurseMedicationChartWhereUniqueInput";
import { NurseMonitoringChartFindManyArgs } from "../../nurseMonitoringChart/base/NurseMonitoringChartFindManyArgs";
import { NurseMonitoringChart } from "../../nurseMonitoringChart/base/NurseMonitoringChart";
import { NurseMonitoringChartWhereUniqueInput } from "../../nurseMonitoringChart/base/NurseMonitoringChartWhereUniqueInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class PatientControllerBase {
  constructor(
    protected readonly service: PatientService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Patient })
  @nestAccessControl.UseRoles({
    resource: "Patient",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createPatient(
    @common.Body() data: PatientCreateInput
  ): Promise<Patient> {
    return await this.service.createPatient({
      data: data,
      select: {
        age: true,
        contactNumber: true,
        createdAt: true,
        gender: true,
        id: true,
        name: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Patient] })
  @ApiNestedQuery(PatientFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Patient",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async patients(@common.Req() request: Request): Promise<Patient[]> {
    const args = plainToClass(PatientFindManyArgs, request.query);
    return this.service.patients({
      ...args,
      select: {
        age: true,
        contactNumber: true,
        createdAt: true,
        gender: true,
        id: true,
        name: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Patient })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Patient",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async patient(
    @common.Param() params: PatientWhereUniqueInput
  ): Promise<Patient | null> {
    const result = await this.service.patient({
      where: params,
      select: {
        age: true,
        contactNumber: true,
        createdAt: true,
        gender: true,
        id: true,
        name: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Patient })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Patient",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updatePatient(
    @common.Param() params: PatientWhereUniqueInput,
    @common.Body() data: PatientUpdateInput
  ): Promise<Patient | null> {
    try {
      return await this.service.updatePatient({
        where: params,
        data: data,
        select: {
          age: true,
          contactNumber: true,
          createdAt: true,
          gender: true,
          id: true,
          name: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Patient })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Patient",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deletePatient(
    @common.Param() params: PatientWhereUniqueInput
  ): Promise<Patient | null> {
    try {
      return await this.service.deletePatient({
        where: params,
        select: {
          age: true,
          contactNumber: true,
          createdAt: true,
          gender: true,
          id: true,
          name: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/doctorProgressNotes")
  @ApiNestedQuery(DoctorProgressNoteFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "DoctorProgressNote",
    action: "read",
    possession: "any",
  })
  async findDoctorProgressNotes(
    @common.Req() request: Request,
    @common.Param() params: PatientWhereUniqueInput
  ): Promise<DoctorProgressNote[]> {
    const query = plainToClass(DoctorProgressNoteFindManyArgs, request.query);
    const results = await this.service.findDoctorProgressNotes(params.id, {
      ...query,
      select: {
        createdAt: true,
        date: true,
        id: true,
        note: true,

        patient: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/doctorProgressNotes")
  @nestAccessControl.UseRoles({
    resource: "Patient",
    action: "update",
    possession: "any",
  })
  async connectDoctorProgressNotes(
    @common.Param() params: PatientWhereUniqueInput,
    @common.Body() body: DoctorProgressNoteWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      doctorProgressNotes: {
        connect: body,
      },
    };
    await this.service.updatePatient({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/doctorProgressNotes")
  @nestAccessControl.UseRoles({
    resource: "Patient",
    action: "update",
    possession: "any",
  })
  async updateDoctorProgressNotes(
    @common.Param() params: PatientWhereUniqueInput,
    @common.Body() body: DoctorProgressNoteWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      doctorProgressNotes: {
        set: body,
      },
    };
    await this.service.updatePatient({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/doctorProgressNotes")
  @nestAccessControl.UseRoles({
    resource: "Patient",
    action: "update",
    possession: "any",
  })
  async disconnectDoctorProgressNotes(
    @common.Param() params: PatientWhereUniqueInput,
    @common.Body() body: DoctorProgressNoteWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      doctorProgressNotes: {
        disconnect: body,
      },
    };
    await this.service.updatePatient({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/nurseMedicationCharts")
  @ApiNestedQuery(NurseMedicationChartFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "NurseMedicationChart",
    action: "read",
    possession: "any",
  })
  async findNurseMedicationCharts(
    @common.Req() request: Request,
    @common.Param() params: PatientWhereUniqueInput
  ): Promise<NurseMedicationChart[]> {
    const query = plainToClass(NurseMedicationChartFindManyArgs, request.query);
    const results = await this.service.findNurseMedicationCharts(params.id, {
      ...query,
      select: {
        createdAt: true,
        date: true,
        id: true,
        medication: true,

        patient: {
          select: {
            id: true,
          },
        },

        time: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/nurseMedicationCharts")
  @nestAccessControl.UseRoles({
    resource: "Patient",
    action: "update",
    possession: "any",
  })
  async connectNurseMedicationCharts(
    @common.Param() params: PatientWhereUniqueInput,
    @common.Body() body: NurseMedicationChartWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      nurseMedicationCharts: {
        connect: body,
      },
    };
    await this.service.updatePatient({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/nurseMedicationCharts")
  @nestAccessControl.UseRoles({
    resource: "Patient",
    action: "update",
    possession: "any",
  })
  async updateNurseMedicationCharts(
    @common.Param() params: PatientWhereUniqueInput,
    @common.Body() body: NurseMedicationChartWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      nurseMedicationCharts: {
        set: body,
      },
    };
    await this.service.updatePatient({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/nurseMedicationCharts")
  @nestAccessControl.UseRoles({
    resource: "Patient",
    action: "update",
    possession: "any",
  })
  async disconnectNurseMedicationCharts(
    @common.Param() params: PatientWhereUniqueInput,
    @common.Body() body: NurseMedicationChartWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      nurseMedicationCharts: {
        disconnect: body,
      },
    };
    await this.service.updatePatient({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/nurseMonitoringCharts")
  @ApiNestedQuery(NurseMonitoringChartFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "NurseMonitoringChart",
    action: "read",
    possession: "any",
  })
  async findNurseMonitoringCharts(
    @common.Req() request: Request,
    @common.Param() params: PatientWhereUniqueInput
  ): Promise<NurseMonitoringChart[]> {
    const query = plainToClass(NurseMonitoringChartFindManyArgs, request.query);
    const results = await this.service.findNurseMonitoringCharts(params.id, {
      ...query,
      select: {
        bp: true,
        createdAt: true,
        date: true,
        id: true,

        patient: {
          select: {
            id: true,
          },
        },

        spo2: true,
        time: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/nurseMonitoringCharts")
  @nestAccessControl.UseRoles({
    resource: "Patient",
    action: "update",
    possession: "any",
  })
  async connectNurseMonitoringCharts(
    @common.Param() params: PatientWhereUniqueInput,
    @common.Body() body: NurseMonitoringChartWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      nurseMonitoringCharts: {
        connect: body,
      },
    };
    await this.service.updatePatient({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/nurseMonitoringCharts")
  @nestAccessControl.UseRoles({
    resource: "Patient",
    action: "update",
    possession: "any",
  })
  async updateNurseMonitoringCharts(
    @common.Param() params: PatientWhereUniqueInput,
    @common.Body() body: NurseMonitoringChartWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      nurseMonitoringCharts: {
        set: body,
      },
    };
    await this.service.updatePatient({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/nurseMonitoringCharts")
  @nestAccessControl.UseRoles({
    resource: "Patient",
    action: "update",
    possession: "any",
  })
  async disconnectNurseMonitoringCharts(
    @common.Param() params: PatientWhereUniqueInput,
    @common.Body() body: NurseMonitoringChartWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      nurseMonitoringCharts: {
        disconnect: body,
      },
    };
    await this.service.updatePatient({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Post("/generate-patient-charts")
  @swagger.ApiOkResponse({
    type: String,
  })
  @swagger.ApiNotFoundResponse({
    type: errors.NotFoundException,
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async GeneratePatientCharts(
    @common.Body()
    body: PatientCreateInput
  ): Promise<string> {
    return this.service.GeneratePatientCharts(body);
  }
}
