/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsInt,
  Min,
  Max,
  IsOptional,
  IsString,
  MaxLength,
  ValidateNested,
  IsEnum,
} from "class-validator";
import { DoctorProgressNoteUpdateManyWithoutPatientsInput } from "./DoctorProgressNoteUpdateManyWithoutPatientsInput";
import { Type } from "class-transformer";
import { EnumPatientGender } from "./EnumPatientGender";
import { NurseMedicationChartUpdateManyWithoutPatientsInput } from "./NurseMedicationChartUpdateManyWithoutPatientsInput";
import { NurseMonitoringChartUpdateManyWithoutPatientsInput } from "./NurseMonitoringChartUpdateManyWithoutPatientsInput";

@InputType()
class PatientUpdateInput {
  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsInt()
  @Min(-999999999)
  @Max(999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  age?: number | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  contactNumber?: string | null;

  @ApiProperty({
    required: false,
    type: () => DoctorProgressNoteUpdateManyWithoutPatientsInput,
  })
  @ValidateNested()
  @Type(() => DoctorProgressNoteUpdateManyWithoutPatientsInput)
  @IsOptional()
  @Field(() => DoctorProgressNoteUpdateManyWithoutPatientsInput, {
    nullable: true,
  })
  doctorProgressNotes?: DoctorProgressNoteUpdateManyWithoutPatientsInput;

  @ApiProperty({
    required: false,
    enum: EnumPatientGender,
  })
  @IsEnum(EnumPatientGender)
  @IsOptional()
  @Field(() => EnumPatientGender, {
    nullable: true,
  })
  gender?: "Option1" | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  name?: string | null;

  @ApiProperty({
    required: false,
    type: () => NurseMedicationChartUpdateManyWithoutPatientsInput,
  })
  @ValidateNested()
  @Type(() => NurseMedicationChartUpdateManyWithoutPatientsInput)
  @IsOptional()
  @Field(() => NurseMedicationChartUpdateManyWithoutPatientsInput, {
    nullable: true,
  })
  nurseMedicationCharts?: NurseMedicationChartUpdateManyWithoutPatientsInput;

  @ApiProperty({
    required: false,
    type: () => NurseMonitoringChartUpdateManyWithoutPatientsInput,
  })
  @ValidateNested()
  @Type(() => NurseMonitoringChartUpdateManyWithoutPatientsInput)
  @IsOptional()
  @Field(() => NurseMonitoringChartUpdateManyWithoutPatientsInput, {
    nullable: true,
  })
  nurseMonitoringCharts?: NurseMonitoringChartUpdateManyWithoutPatientsInput;
}

export { PatientUpdateInput as PatientUpdateInput };
